### PR TITLE
docs: EVM version and metadata hash

### PR DESCRIPTION
**Pull request by hedgar2017**
# What ❔

Fixes https://github.com/matter-labs/era-compiler-solidity/issues/209

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

### CODE REVIEW

**Comment by hedgar2017** [comment]
@antonbaliasnikov fixed `LLVM.lock` here.

**Comment by antonbaliasnikov** [comment]
> @antonbaliasnikov fixed `LLVM.lock` here.

@hedgar2017 , I see the test failures, maybe, LLVM `main` did not contain required fixes yet?

**Comment by hedgar2017** [comment]
> > @antonbaliasnikov fixed `LLVM.lock` here.
> 
> 
> 
> @hedgar2017 , I see the test failures, maybe, LLVM `main` did not contain required fixes yet?

Yeah, let's wait until it's merged.

**Review by PavelKopyl — APPROVED** [review]
LGTM

**Pull request merged**
