### PR TITLE
feat: cumulative update: library linking, recursion fix, a lot of tests

### PR DESCRIPTION
**Pull request by hedgar2017**
# What ❔

1. Fixes the `extra_metadata` serialization.
2. Fixes indeterminism with library linking.
3. Adds tests for *solc* child process errors.
4. Adds tests for a lot of corner use cases of input.
5. Simplifies [de]seriailizeable data structures even more.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

### CODE REVIEW

**Comment by hedgar2017** [comment]
Hey @antonbaliasnikov, it looks like we need to install Rosetta to fix these errors: https://github.com/matter-labs/era-compiler-solidity/actions/runs/11532927790/job/32105256038?pr=183
Is it possible on that runner?

**Comment by hedgar2017** [comment]
Hey @antonbaliasnikov, my bash scripts don't work on Windows as I expected :(
Do you know how to fix? Perhaps, something is off with the shebang line?

**Comment by antonbaliasnikov** [comment]
> Hey @antonbaliasnikov, my bash scripts don't work on Windows as I expected :( Do you know how to fix? Perhaps, something is off with the shebang line?

Hey, I'm taking a look on that.

**Comment by antonbaliasnikov** [comment]
> > Hey @antonbaliasnikov, my bash scripts don't work on Windows as I expected :( Do you know how to fix? Perhaps, something is off with the shebang line?
> 
> Hey, I'm taking a look on that.

@hedgar2017 , this should fix the problem https://github.com/matter-labs/era-compiler-solidity/pull/186

**Review by antonbaliasnikov — APPROVED** [review]
PR is quite huge to review thoroughly, but LGTM.

**Pull request merged**
