### PR TITLE
feat(evm): the EVMLA pipeline

### PR DESCRIPTION
**Pull request by hedgar2017**
# What ❔

Fixes the EVMLA pipeline for EVM target.

## Why ❔

Some deploy code functions were unsupported.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

### CODE REVIEW

**Comment by hedgar2017** [comment]
Hey @PavelKopyl, could you allow `:` in `buffer_ids` for linking?
In EVMLA, these IDs are `{path}:{name}.sol[_deployed]`.

**Comment by PavelKopyl** [comment]
> Hey @PavelKopyl, could you allow `:` in `buffer_ids` for linking? In EVMLA, these IDs are `{path}:{name}.sol[_deployed]`.

Hey @hedgar2017, sure. It looks like we also need to used keccak256(buffer_ids) hex string internally to overcome an issue with invalid symbol names.

**Comment by hedgar2017** [comment]
To merge after merging the branch from LLVM.lock.

**Review by antonbaliasnikov — APPROVED** [review]
LGTM, don't occasionally forget to change the branch back to `main` before merge.

**Comment by hedgar2017** [comment]
> LGTM, don't occasionally forget to change the branch back to `main` before merge.

Hehe, already done! Will fix.

**Pull request merged**
